apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neulander
  namespace: ${neulander_namespace}
  annotations:
    xlscsde.nhs.uk/flux-branch: ${neulander_branch}
spec:
  targetNamespace: ${neulander_namespace}
  releaseName: neulander
  interval: 5m
  chart:
    spec:
      chart: neulander
      version: ${neulander_chart_version}
      sourceRef:
        kind: HelmRepository
        name: neulander
        namespace: ${neulander_namespace}
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  values:
    registryUrl: ghcr.io/lsc-sde
    medcat:
      dummyMode: false
      # tolerations:
      #   - key: "kubernetes.azure.com/scalesetpriority"
      #     operator: "Equal"
      #     value: "spot"
      #     effect: "NoSchedule"
      storage:
        storageClassName: jupyter-default 
        accessModes:
          - ReadOnlyMany
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        xlscsde.nhs.uk/dns-record: neulander${environment_dns_suffix}
      hosts:
        - host: ${environment_dns_prefix}neulander${environment_dns_suffix}.${private_dnz_zone}
      tls:
        enabled: true
        secretName: ${environment_dns_prefix}neulander${environment_dns_suffix}.${private_dnz_zone}-tls
