apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neulander
  namespace: ${neulander_namespace}
  annotations:
    xlscsde.nhs.uk/flux-branch: ${neulander_branch}
spec:
  targetNamespace: ${neulander_namespace}
  releaseName: neulander
  interval: 5m
  chart:
    spec:
      chart: neulander
      version: ${neulander_chart_version}
      sourceRef:
        kind: HelmRepository
        name: neulander
        namespace: ${neulander_namespace}
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  values:
    registryUrl: ghcr.io/lsc-sde
    api:
      image:
        name: neulander-api
        tag: sha256-dfb1bf420957eb2abfd1c67c57a1346eba9c2192399e578011e97c121d30d797
    medcat:
      image:
        name: neulander-medcat-worker
        tag: sha256-0cd17ea5346bac2f2e1223277b4db3152d2ff00736566acc5b3602188900c2fd
      dummyMode: false
      medcatModelPath: /models/medcat_model_pack_v1.4.0.zip
      resources:
        requests:
          memory: "7Gi"
          cpu: "500m"
        limits:
          memory: "10Gi"
          cpu: "1200m"
      # tolerations:
      #   - key: "kubernetes.azure.com/scalesetpriority"
      #     operator: "Equal"
      #     value: "spot"
      #     effect: "NoSchedule"
