apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${environment_dns_prefix}neulander${environment_dns_suffix}.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Neulander API Key"
spec:
  secrets:
    - from: NeulanderAPIKey
      to: neulander-api
    - from: NeulanderRMQNonDefaultUser
      to: neulander-rmq-nondefault-user
