apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: neulander-secrets-distribution
  namespace: ${neulander_namespace}
  annotations:
    xlscsde.nhs.uk/secretUsage: "Neulander Secrets"
spec:
  secrets:
    - from: NeulanderAPIKey
      to: neulander-api
    - from: NeulanderRMQNonDefaultUser
      to: neulander-rmq-nondefault-user
