kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: neulander-fileshare
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=100
  - mfsymlinks
  - cache=strict
  - actimeo=30
  - nosharesock
parameters:
  resourceGroup: lscsdedev-rg
  secretName: neulander-storage
  secretNamespace: neulander
  server: lscsdedevj2zrecy87ltte.privatelink.file.core.windows.net
  skuName: Standard_ZRS
  storageAccount: lscsdedevj2zrecy87ltte
  storeAccountKey: "true"
  # shareName: medcat-models
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neulander-medcat-storage
  namespace: neulander
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: neulander-fileshare
  azureFile:
    secretName: neulander-storage
    secretNamespace: neulander
    shareName: medcat-models
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neulander-medcat-storage
  namespace: neulander
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: neulander-medcat-storage
  storageClassName: neulander-fileshare
  resources:
    requests:
      storage: 5Gi
